import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium } from 'playwright';
const input=path.resolve(process.argv[2]??'reports/economic-demo/index.html');
const output=path.resolve(process.argv[3]??'reports/implementation-20260916/browser');
await fs.mkdir(output,{recursive:true});
const executablePath=process.env.HINDSIGHT_CHROME;
const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];const checks=[];
page.on('pageerror',error=>errors.push(error.message));
const check=(name,condition)=>{assert.ok(condition,name);checks.push(name)};
try {
  await page.goto(pathToFileURL(input).href,{waitUntil:'load'});
  check('Synthetic-data warning is visible',(await page.locator('#warning').innerText()).includes('SYNTHETIC'));
  check('All four research views exist',await page.locator('[role=tab]').count()===4);
  check('Model ladder has four variants',await page.locator('#variant option').count()===4);
  await page.locator('#time').evaluate(e=>{e.value='0';e.dispatchEvent(new Event('input'))});
  check('Future relationship absent at earliest checkpoint',(await page.locator('#edge-count').innerText())==='0');
  await page.locator('[data-tab=evidence]').click();
  check('Future correction text is hidden',!(await page.locator('#sources').innerText()).includes('SYNTHETIC correction'));
  await page.locator('#time').evaluate(e=>{e.value='30';e.dispatchEvent(new Event('input'))});
  check('Historical graph appears after evidence arrives',Number(await page.locator('#edge-count').innerText())>0);
  check('Frozen model lineage is populated',(await page.locator('#lineage').innerText()).includes('model_hash'));
  await page.screenshot({path:path.join(output,'evidence-desktop.png'),fullPage:true});
  await page.locator('[data-tab=replay]').click();
  check('Outcome starts hidden',(await page.locator('#outcome').innerText())==='Outcome hidden.');
  await page.locator('#forecast-note').fill('Regression test note: identify the strongest counterargument.');
  await page.locator('#save-note').click();
  check('Blind-replay notes can be saved',(await page.locator('#note-status').innerText()).includes('Saved'));
  await page.locator('#reveal').click();
  check('Outcome reveal is explicit',(await page.locator('#outcome').innerText()).includes('Realized relative total return'));
  await page.locator('[data-tab=experiments]').click();
  check('Experiment table is populated',await page.locator('#trials tbody tr').count()===4);
  await page.screenshot({path:path.join(output,'experiments-desktop.png'),fullPage:true});
  await page.locator('[data-tab=industry]').click();
  check('Missing production is not fabricated',(await page.locator('#industry').innerText()).includes('Unknown'));
  await page.screenshot({path:path.join(output,'industry-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  check('Mobile page has no horizontal document overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  check('Mobile tables scroll without breaking words into narrow columns',await page.locator('#facts').evaluate(e=>e.scrollWidth>e.clientWidth));
  await page.screenshot({path:path.join(output,'industry-mobile.png'),fullPage:true});
  check('No JavaScript runtime errors',errors.length===0);
  await fs.writeFile(path.join(output,'results.json'),JSON.stringify({passed:checks.length,checks,errors,input},null,2));
  console.log(JSON.stringify({passed:checks.length,errors,output}));
} finally {await browser.close()}
