PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS source_policies(id TEXT NOT NULL,version TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(id,version));
CREATE TABLE IF NOT EXISTS providers(id TEXT PRIMARY KEY,name TEXT NOT NULL,policy_version TEXT NOT NULL,next_allowed_at INTEGER NOT NULL DEFAULT 0,last_error TEXT, FOREIGN KEY(id,policy_version) REFERENCES source_policies(id,version));
CREATE TABLE IF NOT EXISTS dataset_snapshots(id INTEGER PRIMARY KEY AUTOINCREMENT,committed_at INTEGER NOT NULL,description TEXT NOT NULL,manifest_path TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS series(id TEXT PRIMARY KEY,provider TEXT NOT NULL REFERENCES providers(id),known_at INTEGER NOT NULL,created_generation INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS series_versions(series_id TEXT NOT NULL REFERENCES series(id),generation INTEGER NOT NULL,known_at INTEGER NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,entity TEXT NOT NULL,unit TEXT NOT NULL,frequency TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(series_id,generation));
CREATE INDEX IF NOT EXISTS idx_series_versions_name ON series_versions(name,series_id);
CREATE TABLE IF NOT EXISTS entities(id TEXT PRIMARY KEY,kind TEXT NOT NULL,name TEXT NOT NULL,known_at INTEGER NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS instruments(id TEXT PRIMARY KEY,entity_id TEXT NOT NULL,provider TEXT NOT NULL,active INTEGER NOT NULL,known_at INTEGER NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS identifier_versions(instrument_id TEXT NOT NULL,identifier TEXT NOT NULL,valid_from INTEGER,valid_to INTEGER,known_at INTEGER NOT NULL,generation INTEGER NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(instrument_id,identifier,generation));
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,known_at INTEGER NOT NULL,specification TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS calendar_sessions(calendar TEXT NOT NULL,session TEXT NOT NULL,open_ms INTEGER NOT NULL,close_ms INTEGER NOT NULL,version TEXT NOT NULL,PRIMARY KEY(calendar,session,version));
CREATE TABLE IF NOT EXISTS raw_objects(sha256 TEXT PRIMARY KEY,path TEXT NOT NULL,bytes INTEGER NOT NULL,representation TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS captures(id TEXT PRIMARY KEY,provider TEXT NOT NULL REFERENCES providers(id),sha256 TEXT NOT NULL REFERENCES raw_objects(sha256),received_at INTEGER NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS source_documents(id TEXT PRIMARY KEY,capture_id TEXT NOT NULL REFERENCES captures(id),published_at INTEGER,known_at INTEGER NOT NULL,locator TEXT NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS observations(id TEXT PRIMARY KEY,series_id TEXT NOT NULL REFERENCES series(id),period_start TEXT NOT NULL,period_end TEXT NOT NULL,unit TEXT NOT NULL,dimensions TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS observation_versions(id TEXT PRIMARY KEY,natural_key TEXT NOT NULL REFERENCES observations(id),series_id TEXT NOT NULL REFERENCES series(id),period_start TEXT NOT NULL,period_end TEXT NOT NULL,value REAL,unit TEXT NOT NULL,published_at INTEGER,observed_at INTEGER NOT NULL,reconstructed_at INTEGER,source_order INTEGER,capture_id TEXT NOT NULL REFERENCES captures(id),precision TEXT NOT NULL,quality TEXT NOT NULL,generation INTEGER NOT NULL,extras TEXT NOT NULL,semantic_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_observation_lookup ON observation_versions(series_id,period_end,generation,observed_at);
CREATE INDEX IF NOT EXISTS idx_observation_asof ON observation_versions(series_id,observed_at,generation);
CREATE INDEX IF NOT EXISTS idx_observation_recon ON observation_versions(series_id,reconstructed_at,generation);
CREATE INDEX IF NOT EXISTS idx_observation_key ON observation_versions(natural_key,source_order,observed_at);
CREATE TABLE IF NOT EXISTS observation_captures(version_id TEXT NOT NULL REFERENCES observation_versions(id),capture_id TEXT NOT NULL REFERENCES captures(id),PRIMARY KEY(version_id,capture_id));
CREATE TABLE IF NOT EXISTS relationship_versions(id TEXT NOT NULL,revision INTEGER NOT NULL,source_document_id TEXT NOT NULL,known_at INTEGER NOT NULL,valid_from INTEGER NOT NULL,valid_to INTEGER,kind TEXT NOT NULL,from_entity TEXT NOT NULL,to_entity TEXT NOT NULL,status TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(id,revision));
CREATE TABLE IF NOT EXISTS market_bars(id TEXT PRIMARY KEY,version_id TEXT NOT NULL REFERENCES observation_versions(id),symbol TEXT NOT NULL,start_ms INTEGER NOT NULL,end_ms INTEGER NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS corporate_actions(id TEXT PRIMARY KEY,symbol TEXT NOT NULL,effective_at INTEGER NOT NULL,known_at INTEGER NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS partitions(id TEXT PRIMARY KEY,job_id TEXT NOT NULL,path TEXT NOT NULL,sha256 TEXT NOT NULL,rows INTEGER NOT NULL,min_time TEXT,max_time TEXT,generation INTEGER NOT NULL,status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,provider TEXT NOT NULL REFERENCES providers(id),kind TEXT NOT NULL,resource TEXT NOT NULL,params TEXT NOT NULL,state TEXT NOT NULL,cutoff INTEGER NOT NULL,cursor TEXT NOT NULL DEFAULT '{}',attempts INTEGER NOT NULL DEFAULT 0,lease_token TEXT,lease_until INTEGER,priority INTEGER NOT NULL DEFAULT 0,error TEXT,rows INTEGER NOT NULL DEFAULT 0,bytes INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL,not_before INTEGER NOT NULL DEFAULT 0,advertised_total INTEGER,received_rows INTEGER NOT NULL DEFAULT 0,requested_start TEXT,requested_end TEXT,complete_through TEXT);
CREATE INDEX IF NOT EXISTS idx_jobs_claim ON jobs(state,not_before,priority);
CREATE TABLE IF NOT EXISTS job_checkpoints(job_id TEXT NOT NULL REFERENCES jobs(id),cursor_hash TEXT NOT NULL,cursor TEXT NOT NULL,generation INTEGER NOT NULL,committed_at INTEGER NOT NULL,PRIMARY KEY(job_id,cursor_hash));
CREATE TABLE IF NOT EXISTS job_events(id INTEGER PRIMARY KEY AUTOINCREMENT,job_id TEXT NOT NULL REFERENCES jobs(id),at INTEGER NOT NULL,state TEXT NOT NULL,detail TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS request_counts(provider TEXT NOT NULL,day TEXT NOT NULL,count INTEGER NOT NULL,PRIMARY KEY(provider,day));
CREATE TABLE IF NOT EXISTS feature_specs(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS model_artifacts(id TEXT PRIMARY KEY,trained_through INTEGER NOT NULL,known_at INTEGER NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS experiments(id TEXT PRIMARY KEY,state TEXT NOT NULL,created_at INTEGER NOT NULL,scope TEXT NOT NULL,request TEXT NOT NULL,result TEXT,error TEXT,cancel_requested INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS research_results(id TEXT PRIMARY KEY,experiment_id TEXT NOT NULL REFERENCES experiments(id),payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_events(run_id TEXT NOT NULL,sequence INTEGER NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(run_id,sequence));
CREATE TABLE IF NOT EXISTS saved_workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,payload TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS access_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,at INTEGER NOT NULL,action TEXT NOT NULL,scope TEXT NOT NULL,detail TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS replay_notes(id TEXT PRIMARY KEY,at INTEGER NOT NULL,scope TEXT NOT NULL,series_id TEXT NOT NULL,probability REAL NOT NULL CHECK(probability>=0 AND probability<=1),reason TEXT NOT NULL,revealed_at INTEGER);

CREATE TABLE IF NOT EXISTS discovery_outbox(id TEXT PRIMARY KEY,job_json TEXT NOT NULL,page_json TEXT NOT NULL,expanded_at INTEGER);
