import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
const base=process.env.HINDSIGHT_URL??'http://127.0.0.1:8780';
const out=process.argv[2];if(!out)throw new Error('Pass a new output directory');
await fs.mkdir(out,{recursive:false});
const browser=await chromium.launch({headless:true,executablePath:process.env.HINDSIGHT_CHROME??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
const results=[];const a11y=[];let sourceIds=[];let frozen=null;
async function check(name,fn){try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:String(e)});}}
function assert(v,message){if(!v)throw new Error(message);}
async function api(path,options={}){const r=await fetch(base+path,options);const text=await r.text();if(!r.ok)throw new Error(`${r.status}: ${text.slice(0,200)}`);return JSON.parse(text);}
async function navigate(name){if(await page.getByRole('button',{name:'Toggle navigation'}).isVisible())await page.getByRole('button',{name:'Toggle navigation'}).click();await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:new RegExp(name.replace('&','\\&'))}).click();}
async function screenshot(name){await page.screenshot({path:`${out}/${name}.png`,fullPage:true});}
await check('real-data-bootstrap-and-render',async()=>{const b=await api('/api/bootstrap');assert(b.data_kind==='real','Unexpected synthetic startup');frozen={snapshot:b.snapshot,as_of:Date.parse(b.now),mode:'observed',purpose:'display'};await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByRole('heading',{name:'Hindsight Atlas',exact:true}).waitFor();await page.getByRole('button',{name:'Explore outward',exact:true}).waitFor();const atlas=await api('/api/atlas/overview');assert(atlas.scope==='WORLD','Atlas did not default to world scope');assert(atlas.claim.includes('no global completeness'),'Atlas completeness warning missing');await navigate('Overview');await page.getByRole('heading',{name:'Economic observatory',exact:true}).waitFor();await page.getByRole('button',{name:'Inspect ↗'}).first().waitFor();});
await check('real-series-selection-and-chart',async()=>{const q=new URLSearchParams({provider:'worldbank',search:'Exports of goods and services',limit:'200'});const catalog=await api('/api/catalog?'+q);sourceIds=[];for(const row of catalog.rows.filter(r=>r.captured_version_count>=30&&r.frequency==='annual').slice(0,24)){const history=await api('/api/series/'+encodeURIComponent(row.id));if(history.points.filter(p=>p.value!==null).length>=20)sourceIds.push(row.id);if(sourceIds.length===2)break;}assert(sourceIds.length===2,'Two actual annual histories are required');const url=new URL(base);url.searchParams.set('page','Explore');url.searchParams.set('series',sourceIds[0]);await page.goto(url.toString(),{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Add to comparison'}).waitFor();await page.locator('canvas').first().waitFor();const text=await page.locator('.chart-caption').innerText();assert(text.includes('captured periods'),'Actual period count missing');await screenshot('explore-real-desktop');});
await check('source-evidence-drawer-and-keyboard-close',async()=>{await page.getByText('Observation table and source evidence',{exact:true}).click();await page.locator('.series-detail').getByRole('button',{name:'Inspect',exact:true}).first().click();await page.getByRole('heading',{name:'Source evidence',exact:true}).waitFor();await page.locator('.drawer-body').waitFor();assert((await page.locator('.drawer-body').innerText()).includes('Publication'),'Publication evidence missing');await page.keyboard.press('Escape');await page.locator('.drawer').waitFor({state:'detached'});});
await check('workspace-save-and-restore',async()=>{await page.getByRole('button',{name:'Save view',exact:true}).click();const name=`Browser verification ${Date.now()}`;await page.getByLabel('Workspace name',{exact:true}).fill(name);await page.getByRole('button',{name:'Save workspace',exact:true}).click();await page.getByRole('combobox',{name:'Saved workspace'}).locator('option').filter({hasText:name}).waitFor({state:'attached'});await navigate('Overview');await page.getByRole('combobox',{name:'Saved workspace'}).selectOption({label:name});await page.getByRole('heading',{name:'Follow the underlying series',exact:true}).waitFor();assert(new URL(page.url()).searchParams.get('series')===sourceIds[0],'Selected series not restored');});
await check('real-relationship-analysis',async()=>{await page.getByRole('button',{name:'Add to comparison'}).click();await page.getByRole('textbox',{name:'Search the catalog'}).fill('Exports of goods and services');await page.getByLabel('Add a series from current search').selectOption(sourceIds[1]);await page.getByRole('button',{name:'Run analysis',exact:true}).click();await page.getByRole('heading',{name:'Relationship evidence',exact:true}).waitFor({timeout:90000});const text=await page.locator('.result-strip').innerText();assert(text.includes('Descriptive only'),'Inference limits missing');assert(!text.includes('NaN'),'Nonfinite result visible');await screenshot('relationship-real-desktop');});
await check('research-does-not-invent-significance',async()=>{await page.getByText('All tested pairs and methods',{exact:true}).click();assert(await page.getByText('Not justified',{exact:true}).isVisible(),'Unjustified p/q values presented');});
await check('historical-information-is-not-current-backfill',async()=>{await navigate('Explore');await page.getByLabel('Information set',{exact:true}).selectOption('reconstructed');await page.getByLabel('As-of UTC',{exact:true}).fill('2020-01-01T00:00');await page.waitForTimeout(700);await page.locator('.series-detail .error').waitFor();assert(await page.locator('.series-detail canvas').count()===0,'Historical page retained future chart');});
await check('rapid-asof-changes-cannot-restore-stale-result',async()=>{await page.getByLabel('As-of UTC',{exact:true}).fill('2022-01-01T00:00');await page.getByLabel('As-of UTC',{exact:true}).fill('2010-01-01T00:00');await page.waitForTimeout(1000);assert(new URL(page.url()).searchParams.get('as_of').startsWith('2010-'),'Incorrect final scope');assert(await page.locator('.series-detail canvas').count()===0,'Stale response chart leaked');});
await check('return-to-current-observed-view',async()=>{await page.getByLabel('Information set',{exact:true}).selectOption('observed');await page.locator('.scope-bar').getByRole('button').filter({hasText:/Apply latest|Refresh to now/}).click();await page.locator('.series-detail canvas').first().waitFor();});
await check('actual-source-blockers-and-server-filter',async()=>{await navigate('Sources & jobs');await page.getByRole('heading',{name:'Source coverage & access',exact:true}).waitFor();await page.locator('.source-table').getByText('blocked auth',{exact:true}).first().waitFor();assert((await page.locator('.source-table').innerText()).includes('blocked auth'),'Credential blocker absent');await page.locator('.filters').getByLabel('Provider',{exact:true}).selectOption('bls');await page.waitForTimeout(800);const text=await page.locator('main').innerText();assert(text.includes('403')||text.includes('No jobs'),'BLS failure or filtered empty state absent');await screenshot('sources-real-desktop');});
await check('pause-and-resume-controls-change-real-job-state',async()=>{await page.locator('.filters').getByLabel('Provider',{exact:true}).selectOption('worldbank');await page.locator('.filters').getByLabel('State',{exact:true}).selectOption('queued');await page.waitForTimeout(800);const row=page.locator('tbody tr').filter({has:page.getByRole('button',{name:'Pause',exact:true})}).first();const resource=await row.locator('.resource').innerText();await row.getByRole('button',{name:'Pause',exact:true}).click();await page.locator('.filters').getByLabel('State',{exact:true}).selectOption('paused');await page.getByText(resource,{exact:true}).waitFor();const paused=page.locator('tbody tr').filter({has:page.getByText(resource,{exact:true})}).first();await paused.getByRole('button',{name:'Resume',exact:true}).click();await page.getByText(resource,{exact:true}).waitFor({state:'detached'});});
await check('keyboard-search-shortcut',async()=>{await page.keyboard.press('Meta+k');assert(await page.getByRole('textbox',{name:'Search the catalog'}).evaluate(el=>el===document.activeElement),'Search did not gain focus');await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement?.tagName!=='BODY'),'Keyboard focus lost');});
for(const theme of ['light','dark']){for(const width of [1440,1024,390]){await check(`responsive-${theme}-${width}`,async()=>{await page.setViewportSize({width,height:1000});const actual=await page.locator('html').getAttribute('data-theme');if(actual!==theme){if(width<761)await page.getByRole('button',{name:'Toggle navigation'}).click();await page.getByRole('button',{name:theme==='dark'?'Switch to dark theme':'Switch to light theme'}).click();if(width<761)await page.getByRole('button',{name:'Toggle navigation'}).click();}await navigate('Overview');await page.waitForTimeout(500);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+2);assert(!overflow,'Page has unintended horizontal overflow');await screenshot(`overview-${theme}-${width}`);const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();const violations=result.violations.filter(v=>['critical','serious'].includes(v.impact));a11y.push({theme,width,violations:result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,failureSummary:n.failureSummary}))}))});assert(violations.length===0,`${violations.length} serious/critical accessibility violations`);});}}
await check('world-workspace-real-frontier',async()=>{await navigate('World');await page.getByRole('heading',{name:'Hindsight Atlas',exact:true}).waitFor();const atlas=await api('/api/atlas/overview');const cards=await page.locator('.dataset-row').count();assert(cards<=atlas.datasets,'UI invented datasets not present in Atlas catalog');assert((await page.locator('.atlas-map').getAttribute('aria-label'))?.includes('discovered spatial dataset extents'),'World map lacks data-backed accessibility label');await screenshot('world-real-desktop');});
await check('zoom-200-percent-and-reduced-motion',async()=>{await page.setViewportSize({width:1440,height:1000});await navigate('World');await page.evaluate(()=>document.documentElement.style.zoom='2');await page.waitForTimeout(400);await screenshot('zoom-200');assert(await page.getByRole('heading',{name:'Hindsight Atlas',exact:true}).isVisible(),'Main heading lost at zoom');await page.evaluate(()=>document.documentElement.style.zoom='1');});
await check('no-browser-javascript-errors',async()=>assert(errors.length===0,errors.join('\n')));
await fs.writeFile(out+'/browser-results.json',JSON.stringify({base,results,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,errors,a11y,real_source_ids:sourceIds,fixture_results:false},null,2));
await browser.close();console.log(JSON.stringify({passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed),errors},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
