import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import type {Bootstrap,Change,Mode,Scope,Status,Workspace} from './types';
import {useData,request,mutate,scopeQuery,number,bytes,date} from './api';
import {Badge,Drawer,Empty,ErrorBox,Heading,Loading} from './components';
import {Explore} from './Explore';
import {Sources} from './Sources';
import {Research,Experiments} from './Research';
import {Evidence,EvidenceRecord,Replay} from './Evidence';
const pages=['Overview','Explore','Relationships','Sources & jobs','Evidence','Experiments','Replay'] as const;
type Page=typeof pages[number];
const titles:Record<Page,[string,string]>={Overview:['Economic observatory','Original observations, explicit gaps, and a traceable research process.'],Explore:['Follow the underlying series','Product measures, industry indicators, and source definitions before investment hypotheses.'],Relationships:['Inspect the relationship','Separate co-movement, conditional information, and actual economic evidence.'],'Sources & jobs':['Know what you have','Coverage is accounted for. A queued universe is not a completed download.'],Evidence:['What was knowable, and when?','Trace original captures and compare eligible vintages without rewriting history.'],Experiments:['Keep the whole research record','Positive, negative, unsupported, and failed comparisons belong in the ledger.'],Replay:['Make a decision before the reveal','Practice calibrated forecasts using the information actually eligible in the selected view.']};
export default function App(){
 const[boot,setBoot]=useState<Bootstrap|null>(null);const[error,setError]=useState<string|null>(null);const[page,setPage]=useState<Page>(()=>{const p=new URLSearchParams(location.search).get('page');return pages.includes(p as Page)?p as Page:'Overview';});
 const[search,setSearch]=useState('');const[debounced,setDebounced]=useState('');const[mode,setMode]=useState<Mode>('observed');const[asOf,setAsOf]=useState(0);const[snapshot,setSnapshot]=useState(0);const[latest,setLatest]=useState(0);const[selected,setSelected]=useState<string|null>(new URLSearchParams(location.search).get('series'));const[selection,setSelection]=useState<string[]>([]);const[evidence,setEvidence]=useState<string|null>(null);const[dark,setDark]=useState(localStorage.getItem('hindsight-theme')==='dark');const[dense,setDense]=useState(localStorage.getItem('hindsight-density')==='dense');const[tick,setTick]=useState(0);const[menu,setMenu]=useState(false);const[workspace,setWorkspace]=useState('');const[workspaceName,setWorkspaceName]=useState('');const[showSave,setShowSave]=useState(false);const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const a=new AbortController();request<Bootstrap>('/api/bootstrap',{signal:a.signal}).then(b=>{setBoot(b);setSnapshot(b.snapshot);setLatest(b.snapshot);const q=new URLSearchParams(location.search);const t=q.get('as_of');setAsOf(t&&!Number.isNaN(Date.parse(t))?Date.parse(t):Date.parse(b.now));if(q.get('mode')==='reconstructed')setMode('reconstructed');const snap=Number(q.get('snapshot'));if(q.has('snapshot')&&snap>=0&&snap<=b.snapshot)setSnapshot(snap);}).catch(e=>{if(!a.signal.aborted)setError(String(e));});return()=>a.abort();},[]);
 useEffect(()=>{const t=setTimeout(()=>setDebounced(search),180);return()=>clearTimeout(t);},[search]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('hindsight-theme',dark?'dark':'light');},[dark]);
 useEffect(()=>{document.documentElement.dataset.density=dense?'dense':'comfortable';localStorage.setItem('hindsight-density',dense?'dense':'comfortable');},[dense]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus();}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f);},[]);
 useEffect(()=>{if(!boot)return;const events=new EventSource('/api/events');events.addEventListener('watermark',e=>{try{const v=JSON.parse((e as MessageEvent).data) as {snapshot?:number};if(v.snapshot!==undefined)setLatest(v.snapshot);}catch{/* Bad event cannot replace a pinned view. */}});return()=>events.close();},[boot]);
 const scope=useMemo<Scope>(()=>({snapshot,as_of:asOf,mode,purpose:'display'}),[snapshot,asOf,mode]);
 const status=useData<Status>(boot?'/api/status':null,tick);const workspaces=useData<{rows:Workspace[]}>(boot?'/api/workspaces':null,tick);
 const changes=useData<{changes:Change[]}>(boot&&page==='Overview'?`/api/overview?${scopeQuery(scope)}`:null,tick);
 useEffect(()=>{if(!boot||!asOf)return;const q=new URLSearchParams({page,as_of:new Date(asOf).toISOString(),mode,snapshot:String(snapshot)});if(selected)q.set('series',selected);history.replaceState(null,'','?'+q);setEvidence(null);},[boot,page,asOf,mode,snapshot,selected]);
 const refresh=useCallback(async()=>{try{const b=await request<Bootstrap>('/api/bootstrap');setSnapshot(b.snapshot);setLatest(b.snapshot);setAsOf(Date.parse(b.now));setTick(t=>t+1);}catch(e){setError(String(e));}},[]);
 const closeEvidence=useCallback(()=>setEvidence(null),[]);const openEvidence=useCallback((id:string)=>setEvidence(id),[]);
 const navigate=(p:Page)=>{setPage(p);setMenu(false);};
 const addComparison=(id:string)=>{if(selection.includes(id)||selection.length>=8){navigate('Relationships');return;}setSelection([...selection,id]);navigate('Relationships');};
 const saveWorkspace=async()=>{if(!boot)return;try{await mutate('/api/workspaces',boot.token,{name:workspaceName,payload:{page,selected,selection,search,snapshot,asOf,mode}});setTick(t=>t+1);setShowSave(false);setWorkspaceName('');}catch(e){setError(String(e));}};
 const restore=(id:string)=>{setWorkspace(id);const w=workspaces.data?.rows.find(w=>w.id===id);if(!w)return;const v=w.payload;if(pages.includes(v.page as Page))setPage(v.page as Page);setSelected(typeof v.selected==='string'?v.selected:null);if(Array.isArray(v.selection))setSelection(v.selection.filter((x):x is string=>typeof x==='string').slice(0,8));if(typeof v.search==='string')setSearch(v.search);if(typeof v.snapshot==='number')setSnapshot(v.snapshot);if(typeof v.asOf==='number')setAsOf(v.asOf);if(v.mode==='observed'||v.mode==='reconstructed')setMode(v.mode);};
 return <div className={`app ${menu?'menu-open':''}`}><a className="skip-link" href="#main-content">Skip to workspace</a><aside className="sidebar"><a className="brand" href="/" aria-label="Hindsight home"><span className="brand-mark" aria-hidden="true">H<span/></span><span>hindsight<span className="brand-sub">RESEARCH OBSERVATORY</span></span></a><div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{pages.map((p,i)=><button key={p} className={page===p?'active':''} aria-current={page===p?'page':undefined} onClick={()=>navigate(p)}><span className="nav-number">0{i+1}</span>{p}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note">Evidence before conviction.</div><div className="muted">Local workspace<br/>No broker connected</div><button onClick={()=>setDark(!dark)} aria-label={dark?'Switch to light theme':'Switch to dark theme'}>{dark?'Light appearance':'Dark appearance'}</button><button onClick={()=>setDense(!dense)} aria-pressed={dense}>{dense?'Comfortable density':'Compact density'}</button></div></aside>
 <div className="workbench"><header className="global-bar"><button className="mobile-menu" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>☰</button><div className="breadcrumb">Research <span>/</span> {page}</div><label className="global-search"><span className="sr-only">Search the catalog</span><span aria-hidden="true">⌕</span><input ref={searchRef} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find an indicator, product, or entity"/><kbd>⌘ K</kbd></label><button onClick={()=>setShowSave(!showSave)}>Save view</button></header>
 <section className="scope-bar" aria-label="Historical information controls"><label>Information set<select aria-label="Information set" value={mode} onChange={e=>setMode(e.target.value as Mode)}><option value="observed">Observed receipts</option><option value="reconstructed">Reconstructed publication</option></select></label><label>As-of · UTC<input aria-label="As-of UTC" type="datetime-local" step="1" value={asOf?new Date(asOf).toISOString().slice(0,19):''} onChange={e=>{const t=Date.parse(e.target.value+'Z');if(Number.isFinite(t))setAsOf(t);}}/></label><label>Snapshot<input aria-label="Dataset snapshot" type="number" min="0" max={latest} value={snapshot} onChange={e=>setSnapshot(Number(e.target.value))}/></label><button onClick={refresh}>{latest>snapshot?`Apply latest (${latest})`:'Refresh to now'}</button><label className="saved-select"><span className="sr-only">Saved workspace</span><select value={workspace} onChange={e=>restore(e.target.value)}><option value="">Saved views</option>{workspaces.data?.rows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label></section>
 {showSave&&<section className="save-bar"><label>Workspace name<input value={workspaceName} onChange={e=>setWorkspaceName(e.target.value)} maxLength={100}/></label><button className="primary" disabled={!workspaceName.trim()} onClick={saveWorkspace}>Save workspace</button><button onClick={()=>setShowSave(false)}>Cancel</button></section>}
 <main id="main-content" tabIndex={-1}><ErrorBox message={error}/>{!boot&&!error&&<Loading/>}{boot&&<><Heading eyebrow="HINDSIGHT / ECONOMIC INFORMATION" title={titles[page][0]}>{titles[page][1]}</Heading>
 {page==='Overview'&&<><div className="summary-line"><span><strong>{number(status.data?.observation_versions,0)}</strong> captured observation versions</span><span><strong>{number(status.data?.captures,0)}</strong> source captures</span><span><strong>{status.data?.providers.filter(p=>!p.access).length??'—'}</strong> configured open-source families</span></div><div className="overview-grid"><section><div className="section-top"><h2>Latest eligible observations</h2><button onClick={()=>navigate('Explore')}>Explore catalog →</button></div><ErrorBox message={changes.error}/>{changes.loading&&<Loading/>}<div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table><thead><tr><th>Measure / entity</th><th>Period</th><th className="numeric">Value</th><th>Unit</th><th>Evidence</th></tr></thead><tbody>{changes.data?.changes.map(r=><tr key={r.id}><td><button className="row-link" onClick={()=>{setSelected(r.series_id);navigate('Explore');}}>{r.name}</button><small>{r.entity}</small></td><td>{r.period_end}</td><td className="numeric">{number(r.value,3)}</td><td>{r.unit}</td><td><button className="link-button" onClick={()=>openEvidence(r.id)}>Inspect ↗</button></td></tr>)}</tbody></table></div>{changes.data?.changes.length===0&&<Empty title="No observations available at this cutoff">A later capture cannot silently fill an earlier information set. Inspect source coverage or switch to the current observed view.</Empty>}</section><aside className="overview-aside"><div className="eyebrow">COVERAGE NOTEBOOK</div><h2>Incomplete by design, visible by contract.</h2><p>No source family is labeled globally complete. Catalogs, downloaded history, and original-publication evidence are counted separately.</p><dl><dt>Storage</dt><dd>{status.data?bytes(status.data.raw_bytes):'—'} original objects</dd><dt>Disk reserve</dt><dd>{status.data?bytes(status.data.disk_reserve_bytes):'—'}</dd><dt>Free space</dt><dd>{status.data?bytes(status.data.free_bytes):'—'}</dd><dt>Selected clock</dt><dd>{date(asOf)}</dd></dl><button onClick={()=>navigate('Sources & jobs')}>Inspect coverage & blockers</button><hr/><h3>How to investigate</h3><p>Choose an observation. Read its units and source. Compare actual reporting spans. Challenge the relationship before building a forecast.</p><button onClick={()=>navigate('Relationships')}>Open relationship lab</button></aside></div></>}
 {page==='Explore'&&<Explore scope={scope} search={debounced} dark={dark} selected={selected} select={setSelected} compare={addComparison} onEvidence={openEvidence}/>}
 {page==='Relationships'&&<Research scope={scope} dark={dark} token={boot.token} selection={selection} setSelection={setSelection} search={debounced}/>}
 {page==='Sources & jobs'&&<Sources status={status.data} token={boot.token} onChanged={()=>setTick(t=>t+1)}/>}
 {page==='Evidence'&&<Evidence scope={scope} selected={selected} onEvidence={openEvidence}/>}
 {page==='Experiments'&&<Experiments scope={scope} token={boot.token}/>}
 {page==='Replay'&&<Replay key={scopeQuery(scope)} scope={scope} selected={selected} token={boot.token}/>}
 </>}</main><footer><span>Local only · snapshot {snapshot} · {mode}</span><span>Association ≠ causation · No live trading</span></footer></div>
 {evidence&&<Drawer title="Source evidence" onClose={closeEvidence}><EvidenceRecord scope={scope} id={evidence}/></Drawer>}
 </div>;
}
