import {useMemo,useState} from 'react';
import {date,mutate,number,useData} from './api';
import {Badge,Empty,ErrorBox,JsonDetails,Loading} from './components';

type AtlasOverview={scope:string;seeds:number;sources:number;datasets:number;distributions:number;entities:number;edges:number;missions:number;claim:string};
type AtlasDataset={id:string;external_id:string;title:string;description:string;landing_url:string|null;license:string|null;spatial:unknown;temporal:unknown;keywords:unknown;discovered_at:number;source:{url:string;protocol:string;rights_state:string};distributions:number};
type Mission={id:string;query:string;state:string;updated_at:number;requests_used:number;bytes_used:number;datasets_found:number;error:string|null};
type GraphNode={id:string;kind:string;name:string;known_from:number};
type GraphEdge={id:string;layer:string;from:string;to:string;kind:string;known_from:number;evidence_id:string|null};
type Distribution={id:string;url:string;media_type:string|null;format:string|null;profile_status:string|null;profiled_at:number|null;schema:unknown;acquisition:{state:string;policy_id?:string;license?:string;warning?:string;reason?:string}};
type Detail={id:string;title:string;description:string;license:string|null;observation_count:number;distributions:Distribution[]};
type Observation={id:string;series_key:string;period_start:string;period_end:string;value:number;unit:string;dimensions:Record<string,unknown>;observed_at:number;quality:string};
type Props={token:string;search:string;asOf:number;mode:'observed'|'reconstructed'};

function bbox(value:unknown):[number,number,number,number]|null{if(!value||typeof value!=='object')return null;const b=(value as {bbox?:unknown}).bbox;if(!Array.isArray(b)||!Array.isArray(b[0])||b[0].length<4)return null;const v=b[0].slice(0,4).map(Number);return v.every(Number.isFinite)?v as [number,number,number,number]:null;}
function CoverageMap({datasets}:{datasets:AtlasDataset[]}){const boxes=datasets.map(d=>({d,b:bbox(d.spatial)})).filter((x):x is {d:AtlasDataset;b:[number,number,number,number]}=>x.b!==null);const x=(lon:number)=>(lon+180)/360*1000;const y=(lat:number)=>(90-lat)/180*500;return <div className="atlas-map-wrap"><svg viewBox="0 0 1000 500" role="img" aria-label={`World coverage map with ${boxes.length} discovered spatial dataset extents`} className="atlas-map"><rect x="0" y="0" width="1000" height="500" className="map-ocean"/>{[-120,-60,0,60,120].map(l=><line key={'x'+l} x1={x(l)} x2={x(l)} y1="0" y2="500" className="map-grid"/>)}{[-60,-30,0,30,60].map(l=><line key={'y'+l} x1="0" x2="1000" y1={y(l)} y2={y(l)} className="map-grid"/>)}{boxes.slice(0,120).map(({d,b})=>{const[a,c,z,e]=b;return <rect key={d.id} x={x(Math.max(-180,a))} y={y(Math.min(90,e))} width={Math.max(2,x(Math.min(180,z))-x(Math.max(-180,a)))} height={Math.max(2,y(Math.max(-90,c))-y(Math.min(90,e)))} className="map-extent"><title>{d.title}</title></rect>})}</svg>{boxes.length===0&&<div className="map-empty">No spatial extents have been discovered in the current result set. Atlas leaves the map empty instead of inventing locations.</div>}</div>}

export function Atlas({token,search,asOf,mode}:Props){
 const[tick,setTick]=useState(0);const[query,setQuery]=useState(search||'energy');const[busy,setBusy]=useState(false);const[actionError,setActionError]=useState<string|null>(null);const[selected,setSelected]=useState<string|null>(null);
 const overview=useData<AtlasOverview>('/api/atlas/overview',tick);const datasets=useData<{rows:AtlasDataset[]}>(`/api/atlas/datasets?search=${encodeURIComponent(search)}&limit=120`,tick);const graph=useData<{nodes:GraphNode[];edges:GraphEdge[];semantics:string}>(`/api/atlas/graph?search=${encodeURIComponent(search)}&limit=120&as_of=${encodeURIComponent(new Date(asOf).toISOString())}`,tick);const missions=useData<{missions:Mission[]}>('/api/atlas/missions?limit=20',tick);
 const detail=useData<Detail>(selected?`/api/atlas/datasets/${encodeURIComponent(selected)}`:null,tick);const observations=useData<{rows:Observation[];reason?:string;warning?:string}>(selected?`/api/atlas/datasets/${encodeURIComponent(selected)}/observations?mode=${mode}&as_of=${encodeURIComponent(new Date(asOf).toISOString())}&limit=250`:null,tick);const names=useMemo(()=>new Map(graph.data?.nodes.map(n=>[n.id,n.name])??[]),[graph.data]);
 const run=async()=>{setBusy(true);setActionError(null);try{const m=await mutate<{id:string}>('/api/atlas/missions',token,{query,max_requests:8,max_bytes:8388608,max_depth:2,max_sources:20});await mutate(`/api/atlas/missions/${m.id}/run`,token,{});setTick(v=>v+1)}catch(e){setActionError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const acquire=async(id:string)=>{setBusy(true);setActionError(null);try{await mutate(`/api/atlas/distributions/${id}/sample`,token,{max_bytes:8388608});setTick(v=>v+1)}catch(e){setActionError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <div className="atlas-workspace">
  <section className="atlas-command"><div><div className="eyebrow">ATLAS / DISCOVER</div><h2>Explore outward from a world concept</h2><p>Discovery is bounded to reviewed catalogs. Catalog metadata, acquisition permission, downloaded resources and research-ready observations remain separate states.</p></div><div className="atlas-query"><label>Discovery mission<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={200} placeholder="copper, fertilizer, rainfall, memory chips…"/></label><button className="primary" disabled={busy||query.trim().length<2} onClick={run}>{busy?'Working…':'Explore outward'}</button></div><ErrorBox message={actionError}/></section>
  {overview.loading&&<Loading/>}<ErrorBox message={overview.error}/>{overview.data&&<div className="atlas-stats"><span><strong>{number(overview.data.sources,0)}</strong> sources visited</span><span><strong>{number(overview.data.datasets,0)}</strong> datasets catalogued</span><span><strong>{number(overview.data.distributions,0)}</strong> distributions</span><span><strong>{number(overview.data.entities,0)}</strong> graph nodes</span><span><strong>{number(overview.data.edges,0)}</strong> typed edges</span><span><strong>WORLD</strong> default scope</span></div>}
  <div className="atlas-grid"><section><div className="section-top"><div><div className="eyebrow">GEOSPATIAL FRONTIER</div><h2>Actual discovered coverage</h2></div><span className="muted">Spatial metadata only</span></div><CoverageMap datasets={datasets.data?.rows??[]}/></section><aside className="atlas-right"><div className="eyebrow">DISCOVERY FRONTIER</div><h2>Recent missions</h2>{missions.data?.missions.slice(0,8).map(m=><div className="mission-row" key={m.id}><div><strong>{m.query}</strong><small>{date(m.updated_at)} · {m.requests_used} requests · {m.datasets_found} datasets</small></div><Badge state={m.state}/>{m.error&&<small className="warning-text">{m.error}</small>}</div>)}{missions.data?.missions.length===0&&<p className="muted">No discovery missions yet.</p>}</aside></div>
  <section><div className="section-top"><div><div className="eyebrow">DATASET GRAPH</div><h2>Catalogued real-world datasets</h2></div><span className="muted">{datasets.data?.rows.length??0} shown</span></div><ErrorBox message={datasets.error}/>{datasets.loading&&<Loading/>}<div className="atlas-datasets">{datasets.data?.rows.map(d=><article key={d.id} className={`dataset-row ${selected===d.id?'selected':''}`}><div><div className="dataset-title">{d.title}</div><p>{d.description||'No description supplied by source.'}</p><div className="dataset-meta"><Badge state={d.source.rights_state}/><span>{d.source.protocol}</span><span>{d.distributions} distributions</span><span>{date(d.discovered_at)}</span></div></div><div className="dataset-actions"><button onClick={()=>setSelected(d.id)}>Inspect data</button>{d.landing_url&&<a href={d.landing_url} target="_blank" rel="noreferrer">Source ↗</a>}<JsonDetails value={{spatial:d.spatial,temporal:d.temporal,license:d.license,source:d.source}} label="Metadata"/></div></article>)}</div>{datasets.data?.rows.length===0&&<Empty title="No matching Atlas datasets yet">Run a discovery mission. Empty means unknown—not zero and not unavailable.</Empty>}</section>
  {selected&&<section className="atlas-inspector"><div className="section-top"><div><div className="eyebrow">ACQUISITION / EVIDENCE</div><h2>{detail.data?.title??'Loading dataset…'}</h2></div><button onClick={()=>setSelected(null)}>Close</button></div><ErrorBox message={detail.error||observations.error}/>{(detail.loading||observations.loading)&&<Loading/>}{detail.data&&<><p className="muted">{detail.data.observation_count} stored observations. A catalog listing is not treated as acquired data.</p><div className="distribution-list">{detail.data.distributions.slice(0,30).map(d=><div className="distribution-row" key={d.id}><div><strong>{d.format||d.media_type||'resource'}</strong><small>{d.url}</small>{d.profile_status&&<small>profile: {d.profile_status} · {d.profiled_at?date(d.profiled_at):''}</small>}</div><Badge state={d.acquisition.state}/>{d.acquisition.state==='allowed'&&<button disabled={busy||d.profile_status==='validated'} onClick={()=>acquire(d.id)}>{d.profile_status==='validated'?'Acquired':'Acquire bounded sample'}</button>}</div>)}</div>{detail.data.distributions.length>30&&<p className="muted">Showing the first 30 of {detail.data.distributions.length} distributions.</p>}</>}{observations.data?.reason&&<div className="notice">{observations.data.reason}</div>}{observations.data?.warning&&<div className="notice subtle">{observations.data.warning}</div>}{observations.data&&observations.data.rows.length>0&&<div className="table-scroll" tabIndex={0} aria-label="Atlas acquired observation sample"><table><thead><tr><th>Period</th><th>Dimensions</th><th className="numeric">Value</th><th>Unit</th><th>Observed</th></tr></thead><tbody>{observations.data.rows.slice(0,100).map(o=><tr key={o.id}><td>{o.period_end}</td><td><code>{Object.values(o.dimensions).slice(0,3).join(' · ')}</code></td><td className="numeric">{number(o.value,3)}</td><td>{o.unit}</td><td>{date(o.observed_at)}</td></tr>)}</tbody></table></div>}</section>}
  <section><div className="section-top"><div><div className="eyebrow">TEMPORAL GRAPH</div><h2>Relationships known by the selected time</h2></div><span className="muted">{graph.data?.semantics}</span></div><ErrorBox message={graph.error}/><div className="graph-list">{graph.data?.edges.slice(0,40).map(e=><div className="graph-edge" key={e.id}><span>{names.get(e.from)??e.from}</span><strong>{e.kind}</strong><span>{names.get(e.to)??e.to}</span><small>{e.layer} · known {date(e.known_from)}</small></div>)}</div>{graph.data?.edges.length===0&&<Empty title="No graph edges in this information set">Later discoveries are intentionally absent from earlier as-of views.</Empty>}</section>
 </div>
}
