import {useState} from 'react';
import type {Scope,SeriesResponse} from './types';
import {useData,scopeQuery,date,number,mutate} from './api';
import {Empty,ErrorBox,Loading,JsonDetails} from './components';
export function Evidence({scope,selected,onEvidence}:{scope:Scope;selected:string|null;onEvidence:(id:string)=>void}){
 const[compareTime,setCompareTime]=useState('');
 const revisions=useData<{rows:{id:string;period_start:string;period_end:string;value:number|null;unit:string;published_at:number|null;available_at:number|null;quality:string}[]}>(selected?`/api/revisions/${encodeURIComponent(selected)}?${scopeQuery(scope)}`:null);
 const comparisonScope=compareTime?{...scope,as_of:Date.parse(compareTime+'Z')}:null;
 const older=useData<{rows:{id:string;period_end:string;value:number|null;unit:string}[]}>(selected&&comparisonScope&&Number.isFinite(comparisonScope.as_of)?`/api/revisions/${encodeURIComponent(selected)}?${scopeQuery(comparisonScope)}`:null);
 if(!selected)return <Empty title="Select a series in Explore">Its original captures, publication clocks, and eligible revisions will appear here.</Empty>;
 return <><h2 className="mono selected-heading">{selected}</h2><p className="muted">Reporting period, publication, acquisition, and historical availability are different clocks. Captured revisions are retained, not overwritten.</p><ErrorBox message={revisions.error}/>{revisions.loading&&<Loading/>}
 <div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table><thead><tr><th>Reporting span</th><th className="numeric">Value</th><th>Unit</th><th>Published / not before</th><th>Eligible after</th><th>Source</th></tr></thead><tbody>{revisions.data?.rows.map(r=><tr key={r.id}><td>{r.period_start} — {r.period_end}</td><td className="numeric">{number(r.value,5)}</td><td>{r.unit}</td><td>{date(r.published_at)}</td><td>{date(r.available_at)}</td><td><button className="link-button" onClick={()=>onEvidence(r.id)}>Evidence</button></td></tr>)}</tbody></table></div>
 {revisions.data?.rows.length===0&&<Empty title="No eligible version">The system has not captured a version available in this information set.</Empty>}
 <section className="section-gap comparison"><h3>Compare an earlier information set</h3><label>Earlier as-of (UTC)<input type="datetime-local" value={compareTime} onChange={e=>setCompareTime(e.target.value)}/></label><ErrorBox message={older.error}/>{older.loading&&<Loading/>}{older.data&&<><p>{older.data.rows.length} eligible captured versions in the comparison view.</p><div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table><thead><tr><th>Period</th><th>Earlier value</th><th>Unit</th></tr></thead><tbody>{older.data.rows.slice(0,30).map(r=><tr key={r.id}><td>{r.period_end}</td><td>{number(r.value,5)}</td><td>{r.unit}</td></tr>)}</tbody></table></div></>}</section>
 </>;
}
export function EvidenceRecord({scope,id}:{scope:Scope;id:string}){
 const data=useData<{observation:Record<string,unknown>;capture:Record<string,unknown>;series:{name:string;unit:string};policy:{name:string;warning:string}}>(`/api/evidence/${encodeURIComponent(id)}?${scopeQuery(scope)}`);
 return <><ErrorBox message={data.error}/>{data.loading&&<Loading/>}{data.data&&<div className="drawer-body"><div className="eyebrow">{data.data.policy.name}</div><h3>{data.data.series.name}</h3><dl><dt>Value</dt><dd>{number(data.data.observation.value as number|null,6)} {data.data.series.unit}</dd><dt>Period</dt><dd>{String(data.data.observation.period_start)} — {String(data.data.observation.period_end)}</dd><dt>Publication precision</dt><dd>{String(data.data.observation.precision)}</dd><dt>Publication / not before</dt><dd>{date(data.data.observation.published_at as number|null)}</dd><dt>Quality</dt><dd>{String(data.data.observation.quality)}</dd></dl><p className="notice">{data.data.policy.warning}</p>{typeof data.data.capture.url==='string'&&data.data.capture.url.startsWith('https://')&&<a href={data.data.capture.url} target="_blank" rel="noreferrer">Open original source ↗</a>}<JsonDetails value={data.data.observation} label="Exact observation and extraction provenance"/><JsonDetails value={data.data.capture} label="Capture identity and knowledge clocks"/></div>}</>;
}
export function Replay({scope,selected,token}:{scope:Scope;selected:string|null;token:string}){
 const[probability,setProbability]=useState(0.5);const[reason,setReason]=useState('');const[tick,setTick]=useState(0);const[error,setError]=useState<string|null>(null);const[outcome,setOutcome]=useState<unknown>(null);const[busy,setBusy]=useState(false);
 const query=scopeQuery(scope);const notes=useData<{notes:{id:string;series:string;probability:number;reason:string;revealed_at:number|null}[]}>(`/api/replay/notes?${query}`,tick);
 const series=useData<SeriesResponse>(selected?`/api/series/${encodeURIComponent(selected)}?${query}`:null);const latest=series.data?.points.at(-1);
 const save=async()=>{if(!selected)return;setError(null);setBusy(true);try{await mutate('/api/replay/notes',token,{scope,series_id:selected,probability,reason});setTick(t=>t+1);setReason('');}catch(e){setError(String(e));}finally{setBusy(false);}};
 const reveal=async(id:string)=>{setError(null);try{const r=await mutate('/api/replay/reveal',token,{id,scope});setOutcome(r);setTick(t=>t+1);}catch(e){setError(String(e));}};
 return <><div className="notice">Strict API replay: later observations are not included in the information payload. An outcome is requested only after you explicitly reveal it. Notes are not trading instructions.</div><ErrorBox message={error??series.error??notes.error}/>
 {!selected?<Empty title="Choose a research series first">Select an observed series in Explore, then set the global historical as-of time.</Empty>:<div className="replay-grid"><section><div className="eyebrow">Eligible baseline</div><h2>{series.data?.series.name??selected}</h2>{series.loading?<Loading/>:latest?<><div className="replay-value">{number(latest.value,4)}<small>{latest.unit}</small></div><p>{latest.period_start} — {latest.period_end}</p><p className="muted">As-of {date(scope.as_of)} · {scope.mode}</p></>:<Empty title="No eligible observation">Current-vintage backfills cannot populate a historical replay automatically.</Empty>}</section><section className="prediction-form"><h3>Before the next release</h3><label>Probability that the next published value increases<input type="number" step="0.01" min="0" max="1" value={probability} onChange={e=>setProbability(Number(e.target.value))}/></label><label>Reason and what would change your mind<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={5} maxLength={4000}/></label><button className="primary" disabled={busy||!latest||!reason.trim()||probability<0||probability>1} onClick={save}>Record forecast</button></section></div>}
 <section className="section-gap"><h2>Your forecasts in this exact view</h2>{notes.data?.notes.map(n=><article className="note" key={n.id}><div className="section-top"><strong>{number(n.probability*100,0)}% increase probability</strong><button onClick={()=>reveal(n.id)}>{n.revealed_at?'View revealed outcome':'Reveal next observation'}</button></div><p>{n.reason}</p><code>{n.series}</code></article>)}{notes.data?.notes.length===0&&<p className="muted">No notes recorded in this snapshot.</p>}</section>
 {outcome!==null&&<section className="inspector-inline"><h3>Explicit outcome reveal</h3><p>This view may contain information later than the replay cutoff. It is not an input to the forecast.</p><JsonDetails value={outcome} label="Revealed observation and provenance"/><button onClick={()=>setOutcome(null)}>Close outcome</button></section>}
 </>;
}
