import {useEffect,useMemo,useState} from 'react';
import type {Scope,Series,AnalysisEnvelope,Pair} from './types';
import {useData,scopeQuery,mutate,number,date} from './api';
import {Chart} from './Chart';
import {Empty,ErrorBox,Loading,Badge,JsonDetails} from './components';
export function Research({scope,dark,token,selection,setSelection,search}:{scope:Scope;dark:boolean;token:string;selection:string[];setSelection:(v:string[])=>void;search:string}){
 const[transform,setTransform]=useState('change');const[kind,setKind]=useState('dependence');const[lag,setLag]=useState(4);const[start,setStart]=useState('1960-01-01');const[end,setEnd]=useState(new Date().toISOString().slice(0,10));const[job,setJob]=useState<string|null>(null);const[tick,setTick]=useState(0);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[pairIndex,setPairIndex]=useState(0);
 const researchScope=useMemo(()=>({...scope,purpose:'research'}),[scope]);const key=scopeQuery(researchScope);
 const catalog=useData<{rows:Series[]}>(`/api/catalog?${scopeQuery(scope,{search,limit:100})}`);
 const analysis=useData<AnalysisEnvelope>(job?`/api/analyses/${job}?${key}`:null,tick);
 useEffect(()=>{setJob(null);setError(null);},[key]);
 useEffect(()=>{if(job&&(!analysis.data||['queued','running'].includes(analysis.data.state))){const timer=setTimeout(()=>setTick(v=>v+1),1500);return()=>clearTimeout(timer);}},[job,analysis.data,tick]);
 const submit=async()=>{setBusy(true);setError(null);try{const r=await mutate<{id:string}>('/api/analyses',token,{scope:researchScope,series_ids:selection,start,end,kind,transform,max_lag:lag,window:12,controls:[]});setJob(r.id);setTick(t=>t+1);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const cancel=async()=>{if(!job)return;try{await mutate(`/api/analyses/${job}/cancel`,token,{});setTick(t=>t+1);}catch(e){setError(String(e));}};
 const result=analysis.data?.result;const pairs=result?.pairs??[];const pair:Pair|undefined=pairs[pairIndex]??pairs[0];
 const lagLabels=useMemo(()=>pair?.lag_response.map(p=>String(p.lag))??[],[pair]);const lagLines=useMemo(()=>[{name:'Descriptive lag association',values:pair?.lag_response.map(p=>p.pearson)??[]}],[pair]);
 const rollLabels=useMemo(()=>pair?.rolling.map(p=>result?.matched_rows?.[p.end-1]?.period_end??String(p.end))??[],[pair,result]);const rollLines=useMemo(()=>[{name:'Rolling Pearson',values:pair?.rolling.map(p=>p.pearson)??[]}],[pair]);
 return <><div className="research-setup"><section><h2>Declared comparison</h2><p className="muted">Select 2–8 series. Every selected pair and lag stays in the result; no best-correlation selection.</p><div className="selected-series">{selection.map(id=><button key={id} className="selection-chip" onClick={()=>setSelection(selection.filter(x=>x!==id))} title="Remove series">{id}<span aria-hidden="true">×</span></button>)}</div><label className="wide-label">Add a series from current search<select aria-label="Add a series from current search" value="" onChange={e=>{if(e.target.value&&!selection.includes(e.target.value)&&selection.length<8)setSelection([...selection,e.target.value]);}}><option value="">Choose a catalog entry…</option>{catalog.data?.rows.filter(s=>!selection.includes(s.id)).map(s=><option key={s.id} value={s.id}>{s.entity} · {s.name} [{s.frequency}]</option>)}</select></label><p className="muted">Use the global search or add observations from Explore.</p></section>
 <section className="method-form"><label>Research task<select value={kind} onChange={e=>setKind(e.target.value)}><option value="dependence">Descriptive dependence</option><option value="forecast">Release-time forecasting</option><option value="nowcast">Filtered indicator scenario</option></select></label><label>Transform<select value={transform} onChange={e=>setTransform(e.target.value)}><option value="change">Native-period changes</option><option value="log_return">Log change, positive values only</option><option value="level">Levels — exploratory, trend-sensitive</option></select></label><div className="form-pair"><label>Start<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label>Maximum native-period lag<input type="number" min="0" max="12" value={lag} onChange={e=>setLag(Number(e.target.value))}/></label><button className="primary" disabled={busy||selection.length<2||selection.length>8} onClick={submit}>{busy?'Submitting…':'Run analysis'}</button></section></div>
 <ErrorBox message={error??analysis.error}/>{analysis.loading&&!analysis.data&&job&&<Loading/>}
 {analysis.data&&<div className="section-top section-gap"><div><Badge state={analysis.data.state}/><span className="muted mono"> Run {analysis.data.id.slice(0,8)} · pinned snapshot {scope.snapshot}</span></div>{['queued','running'].includes(analysis.data.state)&&<button onClick={cancel}>Cancel analysis</button>}</div>}
 {analysis.data?.error&&<ErrorBox message={analysis.data.error}/>} {analysis.data&&['queued','running'].includes(analysis.data.state)&&<p className="notice">Queued work requires the local supervised worker. The UI does not generate instant or cached substitute results.</p>}
 {result?.state==='insufficient_data'&&<Empty title="Data prerequisites are not met"><p>{result.reason}</p><JsonDetails value={result} label="Exact readiness report"/></Empty>}
 {pair&&<><div className="section-top section-gap"><h2>Relationship evidence</h2><label>Pair<select value={pairIndex} onChange={e=>setPairIndex(Number(e.target.value))}>{pairs.map((p,i)=><option key={p.x+p.y} value={i}>{p.x} ↔ {p.y}</option>)}</select></label></div><div className="result-strip"><div><span>Matched spans</span><strong>{number(pair.samples,0)}</strong></div><div><span>Pearson</span><strong>{number(pair.pearson,3)}</strong></div><div><span>Spearman</span><strong>{number(pair.spearman,3)}</strong></div><div><span>Distance correlation</span><strong>{number(pair.distance_correlation,3)}</strong></div><div><span>Inference</span><strong className="small-stat">Descriptive only</strong></div></div><div className="notice">{pair.inference}. A correlation does not establish a supplier relationship, causality, or trading advantage.</div>
 <div className="chart-grid"><section><h3>Lead / lag profile</h3><Chart labels={lagLabels} lines={lagLines} dark={dark} title="Lag correlations across the complete declared lag family"/><p className="chart-caption">Positive lag pairs earlier X measurement periods with later Y periods. This is not proof X was publicly available first.</p></section><section><h3>Window stability</h3><Chart labels={rollLabels} lines={rollLines} dark={dark} title="Rolling descriptive Pearson correlation"/><p className="chart-caption">Each point uses actual matched spans, not a forward-filled minute panel.</p></section></div>
 {result?.covariance?.partial&&<section className="section-gap"><h3>Shrinkage partial correlations</h3><p className="muted">Estimated Ledoit–Wolf shrinkage {number(result.covariance.shrinkage,4)}. Conditional linear association, not causal identification.</p><div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table className="matrix"><thead><tr><th>Series</th>{selection.map((id,i)=><th key={id} title={id}>{i+1}</th>)}</tr></thead><tbody>{result.covariance.partial.map((row,i)=><tr key={i}><th>{i+1} · {selection[i]}</th>{row.map((v,j)=><td key={j} className={v!==null&&Math.abs(v)>0.5?'matrix-emphasis':''}>{number(v,3)}</td>)}</tr>)}</tbody></table></div></section>}
 <details className="section-gap"><summary>All tested pairs and methods</summary><div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table><thead><tr><th>X</th><th>Y</th><th>N</th><th>Pearson</th><th>Spearman</th><th>Distance</th><th>p / q</th></tr></thead><tbody>{pairs.map(p=><tr key={p.x+p.y}><td>{p.x}</td><td>{p.y}</td><td>{p.samples}</td><td>{number(p.pearson,4)}</td><td>{number(p.spearman,4)}</td><td>{number(p.distance_correlation,4)}</td><td>Not justified</td></tr>)}</tbody></table></div></details>
 </>}
 {result&&result.state==='completed'&&!pair&&<><h2>Research calculation</h2><p className="notice">{result.kind}. This is a research result, not a validated trading strategy.</p><JsonDetails value={result} label="Actual computed output and provenance"/></>}
 {result?.limitations&&<section className="method-notes"><h3>Interpretation limits</h3>{result.limitations.map(s=><p key={s}>{s}</p>)}</section>}
 {!job&&<div className="method-notes"><h3>What this laboratory measures</h3><p>Correlations and distance dependence use matched native periods. Covariance shrinkage is estimated from the actual sample. No p-value or causal direction is invented for irregular, autocorrelated economic observations.</p><p>Release-time forecasts and filtering require enough publication-supported history. A present-day archive of old measurements does not meet that requirement by itself.</p></div>}
 </>;
}
export function Experiments({scope,token}:{scope:Scope;token:string}){
 const[tick,setTick]=useState(0);const[id,setId]=useState<string|null>(null);const researchScope={...scope,purpose:'research'};const query=scopeQuery(researchScope);
 const list=useData<{rows:{id:string;state:string;created_at:number;request:string;error:string|null}[]}>(`/api/analyses?${query}`,tick);const detail=useData<AnalysisEnvelope>(id?`/api/analyses/${id}?${query}`:null,tick);
 useEffect(()=>setId(null),[query]);
 return <><div className="section-top"><h2>Immutable research requests</h2><button onClick={()=>setTick(t=>t+1)}>Refresh</button></div><p className="muted">Only experiments belonging to this exact snapshot, as-of time, evidence mode, and research purpose are listed.</p><ErrorBox message={list.error??detail.error}/>{list.loading&&<Loading/>}
 {list.data?.rows.length===0&&<Empty title="No experiment in this information set">Run a comparison from Relationships. Prior experiments are not silently recomputed against newer data.</Empty>}
 <div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table><thead><tr><th>Run</th><th>Created</th><th>State</th><th>Action</th></tr></thead><tbody>{list.data?.rows.map(r=><tr key={r.id}><td className="mono">{r.id.slice(0,12)}</td><td>{date(r.created_at)}</td><td><Badge state={r.state}/></td><td><button onClick={()=>setId(r.id)}>Inspect</button>{['queued','running'].includes(r.state)&&<button onClick={()=>void mutate(`/api/analyses/${r.id}/cancel`,token,{}).then(()=>setTick(t=>t+1))}>Cancel</button>}</td></tr>)}</tbody></table></div>
 {detail.data&&<section className="inspector-inline"><h3>Run {detail.data.id.slice(0,12)}</h3><ErrorBox message={detail.data.error}/><JsonDetails value={detail.data.request} label="Frozen request"/><JsonDetails value={detail.data.result} label="Result / readiness evidence"/></section>}
 <div className="notice section-gap">The existing trading engine and A/B/C/D offline reports remain separate. No synthetic portfolio return is presented as a real-data experiment here.</div>
 </>;
}
