import {useState} from 'react';
import type {Status,Job} from './types';
import {useData,mutate,number,bytes,date} from './api';
import {Badge,ErrorBox,Loading,JsonDetails,Empty} from './components';
export function Sources({status,token,onChanged}:{status:Status|null;token:string;onChanged:()=>void}){
 const[after,setAfter]=useState('');const[history,setHistory]=useState<string[]>([]);const[provider,setProvider]=useState('');const[state,setState]=useState('');const[tick,setTick]=useState(0);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[inspect,setInspect]=useState<Job|null>(null);
 const q=new URLSearchParams({limit:'100',after,provider,search:state});const jobs=useData<{jobs:Job[]}>(`/api/jobs?${q}`,tick);
 const action=async(id:string,verb:string)=>{setBusy(true);setError(null);try{await mutate(`/api/jobs/${id}/action`,token,{action:verb});setTick(tick+1);onChanged();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const plan=async()=>{setBusy(true);setError(null);try{await mutate('/api/plan',token,{});setTick(tick+1);onChanged();}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <><div className="section-top"><h2>Source coverage & access</h2><button className="primary" disabled={busy} onClick={plan}>Create catch-up plan</button></div><p className="muted">A plan queues declared coverage; it is not a completed download. Provider restrictions and missing credentials never become synthetic data.</p><ErrorBox message={error}/>
 {status===null&&<Loading/>}<div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table className="source-table"><thead><tr><th>Source</th><th>Access</th><th className="numeric">Catalog</th><th className="numeric">Normalized</th><th className="numeric">Committed raw</th><th>Scope & outstanding work</th></tr></thead><tbody>{status?.providers.map(p=><tr key={p.policy.id}><td><strong>{p.policy.name}</strong><a href={p.policy.url} target="_blank" rel="noreferrer">Access policy ↗</a></td><td><Badge state={p.access?.includes('blocked_auth')?'blocked_auth':p.access?'blocked_permission':'enabled'}/></td><td className="numeric">{number(p.catalog_series,0)}</td><td className="numeric">{number(p.committed_rows,0)}</td><td className="numeric">{bytes(p.raw_bytes)}</td><td><details><summary>{p.completed_jobs} / {p.jobs} job scopes complete</summary><p>{p.policy.scope}</p><p>{p.access??p.policy.warning}</p><p>{p.policy.credential_env.length?`Server environment: ${p.policy.credential_env.join(', ')}`:'No key required for this configured source.'}</p><p className="muted">Archive {p.policy.archive?'allowed in declared scope':'blocked'} · research {p.policy.research?'allowed in declared scope':'blocked'} · training {p.policy.training?'allowed in declared scope':'blocked'} · redistribution {p.policy.redistribution?'allowed':'not authorized'}</p><p className="muted">Reviewed {p.policy.reviewed_at}; review due {p.policy.review_due}</p></details></td></tr>)}</tbody></table></div>
 <div className="section-top section-gap"><div><h2>Durable work queue</h2><p className="muted">Leases, checkpoints, and explicit failures are stored on disk.</p></div><button disabled={jobs.loading} onClick={()=>{setTick(tick+1);onChanged();}}>Refresh jobs</button></div>
 <div className="filters"><label>Provider<select aria-label="Provider" value={provider} onChange={e=>{setProvider(e.target.value);setAfter('');setHistory([]);}}><option value="">All providers</option>{status?.providers.map(p=><option key={p.policy.id} value={p.policy.id}>{p.policy.name}</option>)}</select></label><label>State<select aria-label="State" value={state} onChange={e=>{setState(e.target.value);setAfter('');setHistory([]);}}><option value="">All states</option>{['queued','running','paused','retry_wait','blocked_auth','blocked_permission','quarantined','failed','complete_for_declared_scope'].map(v=><option key={v}>{v}</option>)}</select></label></div>
 <ErrorBox message={jobs.error}/>{jobs.loading&&<Loading/>}<div className="table-scroll" tabIndex={0} aria-label="Scrollable data table"><table><thead><tr><th>Source / resource</th><th>State</th><th className="numeric">Accepted rows</th><th>Last checkpoint</th><th>Actions</th></tr></thead><tbody>{jobs.data?.jobs.map(j=><tr key={j.id}><td><strong>{j.provider}</strong><span className="mono resource">{j.resource||'Root catalog'}</span><span className="muted">{j.kind}</span></td><td><Badge state={j.state}/>{j.error&&<div className="job-error">{j.error}</div>}</td><td className="numeric">{number(j.rows,0)}</td><td>{date(j.updated_at)}</td><td className="job-actions"><button onClick={()=>setInspect(j)}>Details</button>{['queued','running','retry_wait'].includes(j.state)&&<button disabled={busy} onClick={()=>action(j.id,'pause')}>Pause</button>}{['paused','failed','quarantined','blocked_auth','blocked_permission','blocked_resources','cancelled'].includes(j.state)&&<button disabled={busy} onClick={()=>action(j.id,'resume')}>Resume</button>}{!['complete_for_declared_scope','cancelled'].includes(j.state)&&<button disabled={busy} onClick={()=>action(j.id,'cancel')}>Cancel</button>}</td></tr>)}</tbody></table></div>
 {jobs.data?.jobs.length===0&&<Empty title="No jobs in this selection">Change the filter or create a declared catch-up plan.</Empty>}
 <div className="pagination"><button disabled={!history.length} onClick={()=>{setAfter(history.at(-1)??'');setHistory(history.slice(0,-1));}}>Previous</button><span>Up to 100 jobs · filtered on server</span><button disabled={jobs.data?.jobs.length!==100} onClick={()=>{setHistory([...history,after]);setAfter(jobs.data?.jobs.at(-1)?.id??'');}}>Next</button></div>
 {inspect&&<section className="inspector-inline"><div className="section-top"><h2>Job checkpoint</h2><button onClick={()=>setInspect(null)}>Close</button></div><p>Frozen cutoff: {date(inspect.cutoff)}</p><JsonDetails value={inspect} label="Complete job record"/></section>}
 <div className="notice">The supervised worker runs only while the local server is running. No public deployment, cloud service, or broker is involved. Never paste API keys into the browser.</div>
 </>;
}
